# This is a basic workflow to help you get started with Actions

name: Toolchain Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Checkout richfelker/musl-cross-make
        uses: actions/checkout@v2
        with:
          repository: richfelker/musl-cross-make
          path: musl-cross-make

      - name: Config and Build
        run: |
          cd musl-cross-make || exit 1
          echo "BINUTILS_VER = 2.32" >> ./config.mak
          echo "GCC_VER = 8.3.0" >> ./config.mak
          echo "MUSL_VER = 1.1.24" >> ./config.mak
          echo "LINUX_VER = headers-4.19.88" >> ./config.mak
          echo "TARGET = x86_64-linux-musl" >> ./config.mak
          echo "GCC_CONFIG += --with-arch=atom" >> ./config.mak
          echo "GCC_CONFIG += --enable-lto --with-gnu-ld" >> ./config.mak
          make -j2
