# This is a basic workflow to help you get started with Actions

name: Toolchain Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code base
        uses: actions/checkout@v2
        with:
          path: toolchain

      - name: Checkout richfelker/musl-cross-make
        uses: actions/checkout@v2
        with:
          repository: richfelker/musl-cross-make
          path: musl-cross-make

      - name: Config and Build
        run: |
          cd musl-cross-make || exit 1
          echo "BINUTILS_VER = 2.32" >> ./config.mak
          echo "GCC_VER = 8.4.0" >> ./config.mak
          echo "MUSL_VER = 1.1.24" >> ./config.mak
          echo "LINUX_VER = headers-4.19.88" >> ./config.mak
          echo "TARGET = arm-linux-musl" >> ./config.mak
          #echo "GCC_CONFIG += --with-arch=atom" >> ./config.mak
          echo "GCC_CONFIG += --with-cpu=cortex-a7 --with-fpu=neon-vfpv4 --with-float=hard" >> ./config.mak
          echo "GCC_CONFIG += --enable-lto --with-gnu-ld" >> ./config.mak
          cp -rf ../toolchain/patches/* patches/
          cp ../toolchain/hashes/* hashes/
          make install -j2

      - name: Pack toolchain
        run: |
          mkdir -p publish
          cd musl-cross-make || exit 1
          mv output arm-none-linux-musl
          tar Jcf ../publish/arm-none-linux-musl.tar.xz arm-none-linux-musl

      - name: Create a release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: arm-toolchain
          release_name: arm-toolchain
          draft: false
          prerelease: false

      - name: Upload toolchain
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./publish/arm-none-linux-musl.tar.xz
          asset_name: arm-none-linux-musl.tar.xz
          asset_content_type: application/octet-stream

